
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer ozyy_create_buffer
#define yy_delete_buffer ozyy_delete_buffer
#define yy_flex_debug ozyy_flex_debug
#define yy_init_buffer ozyy_init_buffer
#define yy_flush_buffer ozyy_flush_buffer
#define yy_load_buffer_state ozyy_load_buffer_state
#define yy_switch_to_buffer ozyy_switch_to_buffer
#define yyin ozyyin
#define yyleng ozyyleng
#define yylex ozyylex
#define yylineno ozyylineno
#define yyout ozyyout
#define yyrestart ozyyrestart
#define yytext ozyytext
#define yywrap ozyywrap
#define yyalloc ozyyalloc
#define yyrealloc ozyyrealloc
#define yyfree ozyyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE ozyyrestart(ozyyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t ozyyleng;

extern FILE *ozyyin, *ozyyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ozyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up ozyytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via ozyyrestart()), so that the user can continue scanning by
	 * just pointing ozyyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when ozyytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t ozyyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ozyywrap()'s to do buffer switches
 * instead of setting up a fresh ozyyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void ozyyrestart (FILE *input_file  );
void ozyy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ozyy_create_buffer (FILE *file,int size  );
void ozyy_delete_buffer (YY_BUFFER_STATE b  );
void ozyy_flush_buffer (YY_BUFFER_STATE b  );
void ozyypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void ozyypop_buffer_state (void );

static void ozyyensure_buffer_stack (void );
static void ozyy_load_buffer_state (void );
static void ozyy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ozyy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ozyy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ozyy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ozyy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *ozyyalloc (yy_size_t  );
void *ozyyrealloc (void *,yy_size_t  );
void ozyyfree (void *  );

#define yy_new_buffer ozyy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ozyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ozyy_create_buffer(ozyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ozyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ozyy_create_buffer(ozyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *ozyyin = (FILE *) 0, *ozyyout = (FILE *) 0;

typedef int yy_state_type;

extern int ozyylineno;

int ozyylineno = 1;

extern char *ozyytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr ozyytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up ozyytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ozyyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[419] =
    {   0,
        0,    0,   80,   78,   77,   76,   78,   78,   68,   78,
       71,   69,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,    0,   73,    0,
        0,   70,   71,    0,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   40,   75,
       75,   75,   74,   75,   75,   75,   75,   75,   75,    0,
       73,    0,   72,   75,   39,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   41,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   45,
       75,   75,   75,   53,   75,    3,   49,   75,   75,   75,

       75,   75,   75,   75,   75,   65,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   67,    4,   75,   75,   75,   75,
       75,   66,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       47,   75,   75,   75,   75,   75,   75,   11,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       19,   75,   75,   75,   75,   75,   17,   75,   75,   75,

       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   14,   75,   75,   75,   75,   12,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   20,   75,   75,   75,   75,   18,   75,   75,   75,
       75,   75,   75,   75,   54,   75,   75,   75,   75,   75,
       75,   75,   15,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   50,   75,   75,    8,
       75,   75,   75,   75,   75,   58,   75,   75,   75,   56,

       55,   75,   75,   75,   75,   75,   75,   64,   13,   75,
       75,   75,   21,   75,   75,   24,   75,   75,   23,   75,
       75,   26,   75,   75,   25,   75,   75,   22,   75,   75,
       51,   75,   75,   75,   75,   75,   60,   59,   75,   75,
       75,    9,   75,   75,   75,   16,   75,   75,   75,   75,
       27,   75,   30,   75,   29,   75,   32,   75,   31,   75,
       28,   75,   52,   48,   75,   75,   75,   75,   75,   57,
       75,   75,   75,   75,   75,   75,   75,   46,   75,   75,
       75,   75,   75,   75,    5,   75,   75,   61,   75,   75,
       75,   10,   75,   75,   75,   42,   33,   36,   35,   38,

       37,   34,    6,   75,   75,   75,   62,   63,   75,   43,
       75,   75,    7,   44,    2,   75,    1,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    8,    9,    1,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,    1,    1,
        1,    1,    1,    1,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,   13,    1,    1,   14,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,   12,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   12,   12,
       12,   12,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[36] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    2,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2
    } ;

static yyconst flex_uint16_t yy_base[423] =
    {   0,
        0,    0,  447,  448,  448,  448,   31,   34,  448,  436,
       30,  448,    0,   23,  414,   27,   24,  429,  416,  414,
       17,  413,  409,   18,   38,   25,  408,   49,  448,   58,
       61,  448,   58,  428,    0,  419,  418,  420,  409,  404,
      416,  396,  405,  396,  413,  392,  401,  392,    0,  395,
      400,  390,  411,   41,  386,  388,   41,  402,  383,   65,
       68,   72,  406,  401,    0,  387,  388,  398,  377,  396,
      376,  394,  389,  387,  391,    0,  390,  376,  380,   58,
      367,  373,  366,  367,  374,   65,  369,   59,  378,  380,
       67,  372,   68,    0,   63,  378,    0,   70,  359,  357,

      375,  374,  373,  355,  367,    0,  365,  356,   72,  349,
      364,  353,  359,  359,  355,  360,  345,   65,   83,  355,
      359,  345,  352,  342,  341,   89,  341,  348,  333,  351,
      332,   90,  346,  335,    0,  347,  339,  332,  338,  338,
      325,    0,  322,  334,  338,  338,  317,  336,  335,  334,
      333,  332,  331,   76,  311,  328,  315,  327,  322,  312,
      305,  322,  321,   94,  302,  306,  306,  313,  298,  302,
        0,  306,  314,  294,  306,  310,  301,    0,  291,  297,
       77,  298,   92,   96,  106,  108,  110,  112,  301,  120,
        0,  294,  286,  286,  298,  297,    0,  289,  296,  284,

      284,  291,  276,  293,  279,  273,  290,  273,  276,  275,
      129,    0,  269,  275,  272,  279,    0,  270,  269,  270,
      267,  274,  259,  264,  271,  256,  261,  268,  253,  258,
      265,  250,  255,  262,  247,  252,  259,  244,  255,  247,
      259,    0,  240,  253,  240,  247,    0,  245,  240,  234,
      251,  234,  247,  238,    0,  237,  238,  228,  241,  230,
      238,  237,    0,  234,  221,  239,  235,  218,  217,  234,
      217,  214,  231,  214,  211,  228,  211,  208,  225,  208,
      205,  222,  205,  202,  219,  202,    0,  199,  214,    0,
      215,  210,  197,  213,  201,    0,  200,  201,  199,    0,

        0,  195,  188,  197,  192,  191,  184,    0,    0,  114,
      188,  192,    0,  189,  190,    0,  187,  188,    0,  185,
      186,    0,  183,  184,    0,  181,  182,    0,  179,  180,
        0,  178,  176,  168,  180,  178,    0,    0,  170,  182,
      174,    0,  163,  119,  172,    0,  177,  160,  163,  162,
        0,  161,    0,  160,    0,  159,    0,  158,    0,  157,
        0,  156,    0,    0,  150,  164,  149,  158,  158,    0,
      158,  161,  142,  141,  148,  138,  153,    0,  149,  148,
      147,  146,  145,  144,    0,  131,  148,    0,  131,  144,
      119,    0,  128,  117,  129,    0,    0,    0,    0,    0,

        0,    0,    0,  106,  115,   87,    0,    0,   99,    0,
       95,   83,    0,    0,    0,   70,    0,  448,  154,  156,
       58,  158
    } ;

static yyconst flex_int16_t yy_def[423] =
    {   0,
      418,    1,  418,  418,  418,  418,  419,  420,  418,  418,
      418,  418,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  419,  418,  422,
      420,  418,  418,  418,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  419,
      419,  422,  418,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,

      421,  421,  421,  421,  421,  421,  421,  421,  421,  421,
      421,  421,  421,  421,  421,  421,  421,    0,  418,  418,
      418,  418
    } ;

static yyconst flex_uint16_t yy_nxt[484] =
    {   0,
        4,    5,    6,    6,    7,    8,    9,   10,    4,   11,
       12,   13,    4,   13,   14,   15,   16,   17,   13,   13,
       13,   18,   19,   13,   20,   21,   22,   23,   24,   13,
       25,   26,   27,   13,   13,   29,   32,   32,   34,   33,
       36,   39,   41,   30,   46,   50,   42,   53,   51,   37,
       47,   52,   40,   29,   56,   80,   54,   57,   58,   35,
       28,   30,   61,   32,   32,   55,   34,   33,   84,   29,
       62,   85,   29,   81,   28,  102,   61,   30,  109,  124,
       30,  112,  103,  149,   62,  117,  113,  118,  417,  114,
      122,  119,  127,  120,  138,  125,  110,  150,  123,  139,

      128,  151,  140,  159,  218,  166,  189,  190,  416,  200,
      219,  160,  167,  415,  221,  152,  201,  414,  224,  413,
      168,  169,  222,  223,  202,  203,  225,  226,  227,  412,
      230,  411,  233,  347,  236,  372,  228,  229,  231,  232,
      234,  235,  237,  238,  240,  260,  348,  410,  409,  408,
      373,  407,  241,  261,   28,   28,   31,   31,   60,   60,
      406,  405,  404,  403,  402,  401,  400,  399,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  371,  370,  369,  368,  367,  366,  365,

      364,  363,  362,  361,  360,  359,  358,  357,  356,  355,
      354,  353,  352,  351,  350,  349,  346,  345,  344,  343,
      342,  341,  340,  339,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  297,  296,  295,  294,  293,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,

      262,  259,  258,  257,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  245,  244,  243,  242,  239,
      220,  217,  216,  215,  214,  213,  212,  211,  210,  209,
      208,  207,  206,  205,  204,  199,  198,  197,  196,  195,
      194,  193,  192,  191,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,
      172,  171,  170,  165,  164,  163,  162,  161,  158,  157,
      156,  155,  154,  153,  148,  147,  146,  145,  144,  143,
      142,  141,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  126,  121,  116,  115,  111,  108,  107,  106,  105,

      104,  101,  100,   99,   98,   97,   96,   95,   94,   93,
       92,   91,   90,   89,   88,   63,   87,   86,   83,   82,
       53,   79,   78,   77,   76,   75,   74,   73,   72,   71,
       70,   69,   68,   67,   66,   65,   64,   63,   59,   49,
       48,   45,   44,   43,   38,   33,  418,    3,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418
    } ;

static yyconst flex_int16_t yy_chk[484] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    7,    8,    8,   11,   11,
       14,   16,   17,    7,   21,   24,   17,   25,   24,   14,
       21,   24,   16,   28,   26,   54,   25,   26,   26,  421,
       30,   28,   30,   31,   31,   25,   33,   33,   57,   60,
       30,   57,   61,   54,   62,   80,   62,   60,   86,   95,
       61,   88,   80,  118,   62,   91,   88,   91,  416,   88,
       93,   91,   98,   91,  109,   95,   86,  118,   93,  109,

       98,  119,  109,  126,  181,  132,  154,  154,  412,  164,
      181,  126,  132,  411,  183,  119,  164,  409,  184,  406,
      132,  132,  183,  183,  164,  164,  184,  184,  185,  405,
      186,  404,  187,  310,  188,  344,  185,  185,  186,  186,
      187,  187,  188,  188,  190,  211,  310,  395,  394,  393,
      344,  391,  190,  211,  419,  419,  420,  420,  422,  422,
      390,  389,  387,  386,  384,  383,  382,  381,  380,  379,
      377,  376,  375,  374,  373,  372,  371,  369,  368,  367,
      366,  365,  362,  360,  358,  356,  354,  352,  350,  349,
      348,  347,  345,  343,  341,  340,  339,  336,  335,  334,

      333,  332,  330,  329,  327,  326,  324,  323,  321,  320,
      318,  317,  315,  314,  312,  311,  307,  306,  305,  304,
      303,  302,  299,  298,  297,  295,  294,  293,  292,  291,
      289,  288,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  272,  271,  270,  269,
      268,  267,  266,  265,  264,  262,  261,  260,  259,  258,
      257,  256,  254,  253,  252,  251,  250,  249,  248,  246,
      245,  244,  243,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  216,  215,  214,

      213,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  196,  195,  194,  193,  192,  189,
      182,  180,  179,  177,  176,  175,  174,  173,  172,  170,
      169,  168,  167,  166,  165,  163,  162,  161,  160,  159,
      158,  157,  156,  155,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  144,  143,  141,  140,  139,  138,  137,
      136,  134,  133,  131,  130,  129,  128,  127,  125,  124,
      123,  122,  121,  120,  117,  116,  115,  114,  113,  112,
      111,  110,  108,  107,  105,  104,  103,  102,  101,  100,
       99,   96,   92,   90,   89,   87,   85,   84,   83,   82,

       81,   79,   78,   77,   75,   74,   73,   72,   71,   70,
       69,   68,   67,   66,   64,   63,   59,   58,   56,   55,
       53,   52,   51,   50,   48,   47,   46,   45,   44,   43,
       42,   41,   40,   39,   38,   37,   36,   34,   27,   23,
       22,   20,   19,   18,   15,   10,    3,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int ozyy_flex_debug;
int ozyy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *ozyytext;
#line 1 "loz.l"
#line 2 "loz.l"
/*
**	Scanner for the Oz simulator.
*/

#undef	_STRING_H

#include	<stdio.h>
#include	<string.h>
#include	"std.h"
#include	"oz.h"
#include	"poz.h"
#include	"missing.h"

#undef	ozyywrap
#define	YY_NO_UNPUT

extern	void	ozyyinit(void);
extern	int	ozyywrap(void);

const char	*ozyyfile = "no input file";
int		ozyylinenum = 0;

extern	int	ozyyget_lineno(void);
extern	FILE	*ozyyget_in(void);
extern	FILE	*ozyyget_out(void);
extern	yy_size_t	ozyyget_leng(void);         /* not type yy_size_t ? */
extern	char	*ozyyget_text(void);
extern	void	ozyyset_lineno(int);
extern	void	ozyyset_in(FILE *);
extern	void	ozyyset_out(FILE *);
extern	int	ozyyget_debug(void);
extern	void	ozyyset_debug(int);
extern	int	ozyylex_destroy(void);

#line 763 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int ozyylex_destroy (void );

int ozyyget_debug (void );

void ozyyset_debug (int debug_flag  );

YY_EXTRA_TYPE ozyyget_extra (void );

void ozyyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *ozyyget_in (void );

void ozyyset_in  (FILE * _in_str  );

FILE *ozyyget_out (void );

void ozyyset_out  (FILE * _out_str  );

yy_size_t ozyyget_leng (void );

char *ozyyget_text (void );

int ozyyget_lineno (void );

void ozyyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ozyywrap (void );
#else
extern int ozyywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( ozyytext, ozyyleng, 1, ozyyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ozyyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ozyyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ozyyin))==0 && ferror(ozyyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ozyyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int ozyylex (void);

#define YY_DECL int ozyylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after ozyytext and ozyyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ozyyin )
			ozyyin = stdin;

		if ( ! ozyyout )
			ozyyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ozyyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ozyy_create_buffer(ozyyin,YY_BUF_SIZE );
		}

		ozyy_load_buffer_state( );
		}

	{
#line 45 "loz.l"


#line 984 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of ozyytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 419 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 448 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "loz.l"
{ return INSTR_PUSH_STACK_FRAME; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "loz.l"
{ return INSTR_POP_STACK_FRAME; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 49 "loz.l"
{ return INSTR_LOAD; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 50 "loz.l"
{ return INSTR_STORE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "loz.l"
{ return INSTR_LOAD_ADDRESS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "loz.l"
{ return INSTR_LOAD_INDIRECT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "loz.l"
{ return INSTR_STORE_INDIRECT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 55 "loz.l"
{ return INSTR_INT_CONST; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "loz.l"
{ return INSTR_REAL_CONST; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 57 "loz.l"
{ return INSTR_STRING_CONST; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 59 "loz.l"
{ return INSTR_ADD_INT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 60 "loz.l"
{ return INSTR_ADD_REAL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "loz.l"
{ return INSTR_ADD_OFFSET; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 62 "loz.l"
{ return INSTR_SUB_INT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 63 "loz.l"
{ return INSTR_SUB_REAL; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 64 "loz.l"
{ return INSTR_SUB_OFFSET; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 65 "loz.l"
{ return INSTR_MUL_INT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 66 "loz.l"
{ return INSTR_MUL_REAL; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 67 "loz.l"
{ return INSTR_DIV_INT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 68 "loz.l"
{ return INSTR_DIV_REAL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 70 "loz.l"
{ return INSTR_CMP_EQ_INT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 71 "loz.l"
{ return INSTR_CMP_NE_INT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "loz.l"
{ return INSTR_CMP_GT_INT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "loz.l"
{ return INSTR_CMP_GE_INT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 74 "loz.l"
{ return INSTR_CMP_LT_INT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 75 "loz.l"
{ return INSTR_CMP_LE_INT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 76 "loz.l"
{ return INSTR_CMP_EQ_REAL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 77 "loz.l"
{ return INSTR_CMP_NE_REAL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 78 "loz.l"
{ return INSTR_CMP_GT_REAL; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 79 "loz.l"
{ return INSTR_CMP_GE_REAL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 80 "loz.l"
{ return INSTR_CMP_LT_REAL; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 81 "loz.l"
{ return INSTR_CMP_LE_REAL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 82 "loz.l"
{ return INSTR_CMP_EQ_STRING; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 83 "loz.l"
{ return INSTR_CMP_NE_STRING; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 84 "loz.l"
{ return INSTR_CMP_GT_STRING; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 85 "loz.l"
{ return INSTR_CMP_GE_STRING; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 86 "loz.l"
{ return INSTR_CMP_LT_STRING; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 87 "loz.l"
{ return INSTR_CMP_LE_STRING; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 89 "loz.l"
{ return INSTR_AND; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 90 "loz.l"
{ return INSTR_OR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "loz.l"
{ return INSTR_NOT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 93 "loz.l"
{ return INSTR_BRANCH_UNCOND; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 94 "loz.l"
{ return INSTR_BRANCH_ON_TRUE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 95 "loz.l"
{ return INSTR_BRANCH_ON_FALSE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "loz.l"
{ return INSTR_CALL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 98 "loz.l"
{ return INSTR_CALL_BUILTIN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "loz.l"
{ return INSTR_RETURN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 101 "loz.l"
{ return INSTR_INT_TO_REAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 103 "loz.l"
{ return INSTR_MOVE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 105 "loz.l"
{ return INSTR_DEBUG_REG; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 106 "loz.l"
{ return INSTR_DEBUG_SLOT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 107 "loz.l"
{ return INSTR_DEBUG_STACK; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 109 "loz.l"
{ return INSTR_HALT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 111 "loz.l"
{ return FUNC_READ_INT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 112 "loz.l"
{ return FUNC_READ_REAL; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 113 "loz.l"
{ return FUNC_READ_BOOL; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 114 "loz.l"
{ return FUNC_READ_STRING; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 116 "loz.l"
{ return FUNC_PRINT_INT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 117 "loz.l"
{ return FUNC_PRINT_REAL; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 118 "loz.l"
{ return FUNC_PRINT_BOOL; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 119 "loz.l"
{ return FUNC_PRINT_STRING; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 121 "loz.l"
{ return FUNC_STRING_CONCAT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 122 "loz.l"
{ return FUNC_STRING_LENGTH; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 123 "loz.l"
{ return FUNC_SUBSTRING; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 125 "loz.l"
{ return FUNC_SQRT; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 126 "loz.l"
{ return FUNC_TRUNC; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 127 "loz.l"
{ return FUNC_ROUND; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 129 "loz.l"
{ return COMMA;	}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 130 "loz.l"
{ return COLON;	}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 132 "loz.l"
{ ozyylinenum++; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 134 "loz.l"
{ ozyylval.Uint = atoi(ozyytext);
			  return NAT_CONST;
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 138 "loz.l"
{ ozyylval.Ureal = atof(ozyytext);
			  return REAL_CONST;
			}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 142 "loz.l"
{ ozyylval.Ustr = strdup(ozyytext);
			  return STRING_CONST;
			}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 146 "loz.l"
{ ozyylval.Uint = atoi(ozyytext+1);
			  return TOKEN_REG;
			}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 150 "loz.l"
{ ozyylval.Ustr = strdup(ozyytext);
			  return TOKEN_ID;
			}
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 154 "loz.l"
{ ozyylinenum++; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 155 "loz.l"
{}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 157 "loz.l"
{ return GARBAGE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 159 "loz.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1449 "<stdout>"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ozyyin at a new source and called
			 * ozyylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ozyyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ozyywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * ozyytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of ozyylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					ozyyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			ozyyrestart(ozyyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) ozyyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 419 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 419 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 418);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up ozyytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					ozyyrestart(ozyyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ozyywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve ozyytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void ozyyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ozyyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ozyy_create_buffer(ozyyin,YY_BUF_SIZE );
	}

	ozyy_init_buffer(YY_CURRENT_BUFFER,input_file );
	ozyy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ozyy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		ozyypop_buffer_state();
	 *		ozyypush_buffer_state(new_buffer);
     */
	ozyyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ozyy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ozyywrap()) processing, but the only time this flag
	 * is looked at is after ozyywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ozyy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ozyyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ozyy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ozyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ozyy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ozyyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ozyy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ozyy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ozyy_create_buffer()
 * 
 */
    void ozyy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ozyyfree((void *) b->yy_ch_buf  );

	ozyyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a ozyyrestart() or at EOF.
 */
    static void ozyy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ozyy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ozyy_init_buffer was _probably_
     * called from ozyyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ozyy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ozyy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void ozyypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ozyyensure_buffer_stack();

	/* This block is copied from ozyy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ozyy_switch_to_buffer. */
	ozyy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void ozyypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ozyy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ozyy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ozyyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)ozyyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ozyyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)ozyyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ozyyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ozyy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ozyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ozyy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ozyy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to ozyylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ozyy_scan_bytes() instead.
 */
YY_BUFFER_STATE ozyy_scan_string (yyconst char * yystr )
{
    
	return ozyy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to ozyylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ozyy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ozyyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ozyy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = ozyy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ozyy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up ozyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		ozyytext[ozyyleng] = (yy_hold_char); \
		(yy_c_buf_p) = ozyytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ozyyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ozyyget_lineno  (void)
{
        
    return ozyylineno;
}

/** Get the input stream.
 * 
 */
FILE *ozyyget_in  (void)
{
        return ozyyin;
}

/** Get the output stream.
 * 
 */
FILE *ozyyget_out  (void)
{
        return ozyyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t ozyyget_leng  (void)
{
        return ozyyleng;
}

/** Get the current token.
 * 
 */

char *ozyyget_text  (void)
{
        return ozyytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void ozyyset_lineno (int  _line_number )
{
    
    ozyylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see ozyy_switch_to_buffer
 */
void ozyyset_in (FILE *  _in_str )
{
        ozyyin = _in_str ;
}

void ozyyset_out (FILE *  _out_str )
{
        ozyyout = _out_str ;
}

int ozyyget_debug  (void)
{
        return ozyy_flex_debug;
}

void ozyyset_debug (int  _bdebug )
{
        ozyy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from ozyylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ozyyin = stdin;
    ozyyout = stdout;
#else
    ozyyin = (FILE *) 0;
    ozyyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * ozyylex_init()
     */
    return 0;
}

/* ozyylex_destroy is for both reentrant and non-reentrant scanners. */
int ozyylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ozyy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		ozyypop_buffer_state();
	}

	/* Destroy the stack itself. */
	ozyyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * ozyylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ozyyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *ozyyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ozyyfree (void * ptr )
{
			free( (char *) ptr );	/* see ozyyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 159 "loz.l"



void ozyyinit(void)
{
}

int ozyywrap(void)
{
	return 1;
}

